machine.wait_for_unit("webauthn-tiny.service")
machine.wait_for_open_port(8080)
machine.fail("curl -v --fail [::1]:8080/authenticate")
machine.fail("curl -v --fail -u user:wrong_password [::1]:8080/authenticate")
machine.succeed("curl -v --fail -u user:password [::1]:8080/authenticate")
